version: '3'
services:
  redis:
    image: 'rabbitmq:3.7-management-alpine'
    container_name: "rabbitmq-3.7-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/.docker-volumes/spring-boot-2-example/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
